### PR TITLE
Implement ui

### PR DESCRIPTION
**Pull request by Paramveer12**
Screenshot_2020-06-02 TodoList

### CODE REVIEW

**Comment by lakshay-angrish** [comment]
Could you add screenshots in the description?

**Comment by wayne9499** [comment]
yes, in ur commit half of lines are boilerplate test file code. I think there isn't any need of new components.

**Comment by Paramveer12** [comment]
Why are components unnecessary? They are going to be used many times with different values.

**Comment by lakshay-angrish** [comment]
This way we would have to create a new component for every task and delete them when a task is deleted. We should create one component, wherein we would iterate over every task and create one div or container of some kind, for each task. And this is much less complex.

**Comment by Paramveer12** [comment]
And there is only one component of task

**Comment by wayne9499** [comment]
this is not how it works @Paramveer12.. there exists a for loop for that kinda repetition work

**Comment by Paramveer12** [comment]
What are you guy trying to say, can y'all speak clearly

**Comment by wayne9499** [comment]
we can iterate over the array of JSON objects and create dynamic list to show the whole info at one go.. and that only takes one parent div to show current and one div to show upcoming events/todos

**Comment by Paramveer12** [comment]
So you are saying they should be static?

**Comment by Paramveer12** [comment]
I created 2 components. Is any of them unnecessary? If yes, which one?

**Comment by Paramveer12** [comment]
This is taking too long

**Comment by wayne9499** [comment]
its not durable for later work.. coz we can do this on divs in a simple way.. why are u making this so complex

**Pull request merged**
